config/routes.rb
Rails.application.routes.draw do
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    passwords:     'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :new, :create]
  end
  resources :farms, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :tags, only: :show
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :farmer
  has_many_attached :images
  has_many :farm_tags, dependent: :destroy
  has_many :tags, through: :farm_tags, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, dependent: :destroy
  has_many :tweets
  
  validates :farmer_id, uniqueness: true
  validates :name, :images, :description, :feature, :prefecture_id, presence: true
  validates :prefecture_id, numericality: { other_than: 1 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:text) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old_text|
      self.tags.delete Tag.find_by(text: old_text)
    end

    new_tags.each do |new_text|
      farm_tag = Tag.find_or_create_by(text: new_text)
      self.tags << farm_tag
    end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_farmer!, only: :new
  before_action :move_to_root, only: [:edit, :destroy]

  def new
    @farm = Farm.new
  end

  def create
    @farm = Farm.new(farm_params)
    if params[:farm][:text]
      tag_list = params[:farm][:text].split(",")
    end
    if @farm.save
      @farm.save_tag(tag_list)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @farm_tags = @farm.tags
    @farmer = @farm.farmer
    @room = Room.new
  end

  def edit
    @tag_list = @farm.tags.pluck(:text).join(",")
  end

  def update
    if params[:farm][:image_ids]
      params[:farm][:image_ids].each do |image_id|
        image = @farm.images.find(image_id)
        image.purge
      end
    end
    if farm_params[:images]
      @farm.images.attach(farm_params[:images])
    end
    if params[:farm][:text]
      tag_list = params[:farm][:text].split(",")
    end
    if @farm.update(name: farm_params[:name], prefecture_id: farm_params[:prefecture_id], description: farm_params[:description], feature: farm_params[:feature], farmer_id: farm_params[:farmer_id])
      @farm.save_tag(tag_list)  
      redirect_to farm_path(@farm.id)
    else
      render :edit
    end
  end

  def destroy
    if @farm.destroy
      redirect_to root_path
    else
      redirect_to farm_path(@farm)
    end
  end

  private

  def farm_params
    params.require(:farm).permit(:name, :prefecture_id, :description, :feature, images: []).merge(farmer_id: current_farmer.id)
  end

  def set_farm
    @farm = Farm.find(params[:id])
  end

  def move_to_root
    return if farmer_signed_in? && current_farmer.id == @farm.farmer_id

    redirect_to root_path
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/edit.html.erb
<%= render partial: 'shares/bar_menu_second' %>
<h2 class="sign-head">農園紹介編集</h2>

<%= form_with model: @farm, local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>
  <div class="box-farm-edit">
    <div class="box-inner">
      <div class='box-text'>
        <%= form.label :name, '農園名もしくは法人名、個人の生産者様はお名前フルネーム' %><br>
        <%= form.text_field :name, placeholder:'(例)せせらぎ農園', size: '40x2' %>
      </div>
      <div class='box-text'>
        <%= form.label :text, '販売予定品目を全角カタカナで入力して下さい(品名の間には半角の,を入力して下さい)' %>
        <%= form.text_field :text, value: @tag_list, size: '40x1' %>
      </div>
      <div class='box-text'>
        <%= form.label :images, '紹介画像(4枚まで選択可)' %>
        <ul>
          <li><%= form.file_field :images, multiple: true, id:'farm-image1' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image2' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image3' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image4' %></li>
        </ul>
      </div>
      <div id='image-list'></div>
      <%if @farm.images.present? %>
        <p>現在登録されている画像(削除するものはチェックしてください)</p>
        <% @farm.images.each do |image| %>
          <%= form.check_box :image_ids, {multiple: true}, image.id, false %>
          <%= image_tag image.variant(resize:'150x150') %><br>
        <% end %>
      <% end %>
      <div class='box-select'>
        <%= form.label :prefecture_id, '都道府県'%><br>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {})%>
      </div>
      <div class='box-text'>
        <%= form.label :description, '紹介文' %><br>
        <%= form.text_area :description, placeholder:'農園の紹介', size: '80x10' %>
      </div>
      <div class='box-text'>
        <%= form.label :feature, 'ここがこだわり' %><br>
        <%= form.text_area :feature, placeholder:'こだわっている事、農園の特徴', size: '80x10' %>
      </div>
      <div class='box-submit'>
        <%= form.submit '更新' %>
      </div>
    </div>
  </div>
<% end %>

app/views/farms/new.html.erb
<%= render partial: 'shares/bar_menu_second' %>
<h2 class="sign-head">農園紹介新規作成</h1>

<%= form_with model: @farm, local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>
  <div class="box-farm">
    <div class="box-inner">
      <div class='box-text'>
        <%= form.label :name, '農園名もしくは法人名、個人の生産者様はお名前フルネーム' %><br>
        <%= form.text_field :name, placeholder:'(例)せせらぎ農園' %>
      </div>
      <div class='box-text'>
        <%= form.label :text, '販売予定品目を全角カタカナで入力して下さい(品名の間には半角の,を入力して下さい)' %>
        <%= form.text_field :text, placeholder:'(例)タマネギ,ニンジン,トマト' %>
      </div> 
      <div class='box-text'>
        <%= form.label :images, '紹介画像(4枚まで選択可)' %>
        <ul>
          <li><%= form.file_field :images, multiple: true, id:'farm-image1' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image2' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image3' %></li>
          <li><%= form.file_field :images, multiple: true, id:'farm-image4' %></li>
        </ul>
      </div>
      <div id='image-list'></div>
      <div class='input-birth-wrap'>
        <%= form.label :prefecture_id, '都道府県'%><br>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {})%>
      </div>
      <div class='box-text'>
        <%= form.label :description, '紹介文' %><br>
        <%= form.text_area :description, placeholder:'農園の紹介', size: '80x10' %>
      </div>
      <div class='box-text'>
        <%= form.label :feature, 'ここがこだわり' %><br>
        <%= form.text_area :feature, placeholder:'こだわっている事、農園の特徴', size: '80x10' %>
      </div>
      <div class='box-submit'>
        <%= form.submit '作成' %>
      </div>
    </div>
  </div>
<% end %>

app/views/farms/show.html.erb
<%= render partial: 'shares/bar_menu' %>
<h1 class="farm-big-title">＜農園紹介＞</h1>
<div class="farm-favorite">
  <h3 class="farm-middle-title"><%= @farm.name %><h3>
  <div id="farm_<%= @farm.id %>">
    <%= render partial: "shares/favorite", locals: { farm: @farm } %>
  </div>
</div>
<% if user_signed_in? %>
  <%= form_with model: @room, local: true do |form| %>
    <input value=<%=@farm.farmer.id%> type="hidden" name='farmer_id'>
    <%= form.submit "チャットルーム作成"%>
  <% end %>
<% end %>
<% if current_farmer == @farm.farmer %>
  <%= link_to '紹介ページ編集', edit_farm_path(@farm.id), class:"farm-show-button" %>
  <%= link_to '紹介ページ削除', farm_path(@farm), class:"farm-show-button intro-destroy", method: :delete %>
  <%= link_to 'ツイート作成', new_farm_tweet_path(@farm), class:"farm-show-button tweet-create" %>
<% end %>
<%= link_to 'ツイート一覧', farm_tweets_path(@farm), class:"farm-show-button tweet-list" %>
<h4 class="farm-small-title">生産品目</h4>
<div class="item-tag">
  <% @farm_tags.each do |tag| %>
    <%= "#{tag.text} " %>
  <% end %> 
</div>
<h4 class="farm-small-title">生産地</h4>
<div class="item-tag"><%= @farm.prefecture.name %></div>

<div class="farm-images">
  <% i = 0 %>
  <div class="farm-images-all">
    <% @farm.images.each do |image| %>
      <div class="farm-images-each">
        <% if i != 0 %>
          <%= image_tag image.variant(resize:'300x400'), class:"farm-other-images" %>
        <% else %>
          <%= image_tag image.variant(resize:'600x700'), class:"farm-first-image" %><br>
      </div>
        <% end %>
      <% i += 1 %>
    <% end %>
  </div>
</div>
<h4 class="farm-small-title" >農園紹介</h4>
<div>
  <%= @farm.description %>
</div>
<h4 class="farm-small-title">ここがこだわり</h4>
<div>
  <%= @farm.feature %>
</div>
<h4 class="farm-small-title">販売品目</h4>
<div class="main-bar-bottom">
  <% @farmer.items.each do |item| %>
    <%= render "shares/each_item", item: item %>
  <% end %>
</div>