config/routes.rb
Rails.application.routes.draw do
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    passwords:     'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :new, :create]
  end
  resources :farms, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :tags, only: :show
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/farm.rb
class Farm < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :farmer
  has_many_attached :images
  has_many :farm_tags, dependent: :destroy
  has_many :tags, through: :farm_tags, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, dependent: :destroy
  has_many :tweets
  
  validates :farmer_id, uniqueness: true
  validates :name, :images, :description, :feature, :prefecture_id, presence: true
  validates :prefecture_id, numericality: { other_than: 1 }

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:text) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old_text|
      self.tags.delete Tag.find_by(text: old_text)
    end

    new_tags.each do |new_text|
      farm_tag = Tag.find_or_create_by(text: new_text)
      self.tags << farm_tag
    end
  end
end

app/models/farm_tag.rb
class FarmTag < ApplicationRecord
  belongs_to :farm
  belongs_to :tag
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

attr_accessor :organic
validates_acceptance_of :organic, allow_nil: false, on: :create, message: '有機農産物のみの販売に同意が必要です'
validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_date, presence: true
validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
validates :last_name_kana, format: { with: /\A[ァ-ン]+\z/ }
validates :first_name_kana, format: { with: /\A[ァ-ン]+\z/ }

has_one :farm
has_many :items
has_many :rooms
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :farm
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :farmer
  has_one_attached :image
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :period
  belongs_to_active_hash :ship_expense
  has_many :orders, dependent: :destroy

  validates :name, :image, :description, :ship_expense_id, :prefecture_id, :period_id, :price, presence: true
  validates :ship_expense_id, :prefecture_id, :period_id, numericality: { other_than: 1 }
  validates :name, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角カタカナで入力して下さい' }
  validates :price, format: { with: /\A[0-9]+\z/ }
  validates :price, numericality: { greater_than_or_equal_to: 100 }

  def self.search(search)
    if search != ""
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :content, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address, dependent: :destroy
end

app/models/period.rb
class Period < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '翌日発送' },
    { id: 3, name: '2~3日で発送' },
    { id: 4, name: '4~7日で発送' }
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福島県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/room.rb
class Room < ApplicationRecord
  validates :user_id, uniqueness: {scope: :farmer_id}

  belongs_to :user
  belongs_to :farmer
  has_many :messages, dependent: :destroy
end

app/models/ship_expense.rb
class ShipExpense < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い(購入者負担)' },
    { id: 3, name: '送料込み(出品者負担)' }
  ]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :farm_tags, dependent: :destroy
  has_many :farms, through: :farm_tags, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, :image, presence: true

  belongs_to :farm
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_date, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
  validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
  validates :last_name_kana, format: { with: /\A[ァ-ン]+\z/ }
  validates :first_name_kana, format: { with: /\A[ァ-ン]+\z/ }

  has_many :favorites, dependent: :destroy
  has_many :farms, through: :favorites, dependent: :destroy
  has_many :rooms
  has_many :orders, dependent: :destroy

  def already_favorite?(farm)
    self.favorites.exists?(farm_id: farm.id)
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shares/_bar_menu.html.erb
<div class='bar-logo'>
        <%= link_to image_tag('farmdeli.png', class:"farmdeli"), root_path %>
</div>
<div class='bar'>
<div class='bar-below'>
  <% if user_signed_in? %>
  <div class='farmer-login'>
    <ul class='lists-left'>
      <li><%= link_to current_user.nickname, '#', class:'bar-link name' %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'bar-link login-out' %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to 'マイページ', user_path(current_user.id), class:'bar-link my-favorite' %></li>
      <li><%= link_to 'チャットルーム一覧', rooms_path, class:'bar-link my-favorite' %></li>
    </ul>
  </div>
  <% elsif farmer_signed_in? %>
    <div class='farmer-login'>
    <ul class='lists-left'>
      <li><%= link_to current_farmer.nickname, '#', class:'bar-link name' %></li>
      <li><%= link_to 'ログアウト', destroy_farmer_session_path, method: :delete, class:'bar-link login-out' %></li>
    </ul>
    <ul class='lists-right'>
      <% unless current_farmer.farm %>
        <li><%= link_to '農園紹介ページ作成', new_farm_path, class:'bar-link my-favorite' %><li>
      <% end%>
      <li><%= link_to 'チャットルーム一覧', rooms_path, class:'bar-link my-favorite' %><li>
      <li><%= link_to '商品出品', new_item_path, class:"new-item-link" %></li>
    </ul>
    </div>
  <% else %>
  <div class='bar-before'>
    <ul class='lists-left'>
      <li><%= link_to 'お客様新規登録', new_user_registration_path, class:'bar-link login-out' %></li>
      <li><%= link_to 'お客様ログイン', new_user_session_path, class:'bar-link login-out' %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to '生産者様新規登録', new_farmer_registration_path, class:'bar-link log-farmer' %></li>
      <li><%= link_to '生産者様ログイン', new_farmer_session_path, class:'bar-link log-farmer' %></li>
    </ul>
    </div>
  <% end %>
  </div>
</div>

app/views/shares/_bar_menu_second.html.erb
<div class='bar-logo'>
  <%= link_to image_tag('farmdeli.png', class:"farmdeli"), root_path %>
</div>

app/views/shares/_category.html.erb
<h4 class="category-title">品目別農園カテゴリー<h4>
  <ul class="category-lists">
  <% tags.each do |tag| %>
    <li class="category-list"><%= link_to "#{tag.text}生産農園", tag_path(tag.id), class:"category-link" %></li>
  <% end %>
  </ul>

app/views/shares/_each_farm.html.erb
<div class="each-farm">
  <%= farm.name %>
  <%= link_to farm_path(farm), class:"each-farm-name" do %><br>
    <%= image_tag farm.images.first, class:"farm-image" %><br>
    ＜生産品目＞<br>
    <% farm.tags.each do |tag| %>
      <div class="each-farm-tag"><%= "#{tag.text} " %></div>
    <% end %>
  <% end %>
</div>

app/views/shares/_each_item.html.erb
<div class="each-item">
  <%= link_to item_path(item) do %>
    <%= image_tag item.image, class:"item-image" %><br>
    <%= item.description %><br>
    <%= item.prefecture.name %>産<%= "  #{item.price}" %>円<br>
  <% end %>
</div>

app/views/shares/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" >
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shares/_favorite.html.erb
<% if user_signed_in? %>
  <% if current_user.already_favorite?(farm) %>
    <%= link_to farm_favorite_path(farm, current_user.id), class: "like-link", method: :delete, remote: true do %>
      <i class="far fa-thumbs-up unlike-btn"></i>
    <% end %><%= farm.favorites.count %>
  <% else %>
    <%= link_to farm_favorites_path(farm), class: "like-link", method: :post, remote: true do %>
      <i class="far fa-thumbs-up like-btn"></i>
    <% end %><%= farm.favorites.count %>
  <% end %>
<%end%>
<% unless user_signed_in? %>
  <%= link_to farm_favorites_path(farm), class: "like-link", method: :post do %>
    <i class="far fa-thumbs-up like-btn"></i>
  <% end %><%= farm.favorites.count %>
<%end%>