config/routes.rb
Rails.application.routes.draw do
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    passwords:     'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :new, :create]
  end
  resources :farms, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :tags, only: :show
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, :image, presence: true

  belongs_to :farm
  has_one_attached :image
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_farm, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :move_to_root, only: [:new, :create, :edit, :update, :destroy]

  def index
    @tweets = @farm.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.farm_id = @farm.id
    if @tweet.save
      redirect_to farm_tweets_path(@farm)
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to farm_tweets_path(@farm)
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      redirect_to farm_tweets_path(@farm)
    else
      redirect_to farm_tweets_path(@farm)
    end
  end


  private

  def tweet_params
    params.require(:tweet).permit(:content, :image)
  end

  def set_farm
    @farm = Farm.find(params[:farm_id])
  end

  def move_to_root
    return if farmer_signed_in? && current_farmer.farm.id == @farm.id

    redirect_to root_path
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%= render 'shares/bar_menu_second' %>
<h2 class="tweet-new-title">ツイート編集ページ</h2>

  <%= form_with model: [@farm, @tweet], local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>

  <div class="tweet-new">
    <div class="tweet-inner">
      <div class='tweet-text'>
        <%= form.label :content, 'ツイート記事を入力して下さい' %><br>
        <%= form.text_area :content %>
      </div>
      <div class="tweet-image">
        <%= form.label :image, 'ツイート画像を選択して下さい(1個)' %><br>
        <%= form.file_field :image, id: 'farm-image1' %>
      </div>
      <div id='image-list'></div>
      <div class='tweet-submit'>
        <%= form.submit '作成' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/index.html.erb
<%= render 'shares/bar_menu' %>
<h2 class="tweet-new-title">ツイート一覧</h2>
<h3 class="tweet-new-title"><%=@farm.name%></h3>
<div class="tweet-index">
  <div class="tweet-index-inner">
    <% @tweets.each do |tweet| %>
      <div class="tweet-index-image" >
        <%= image_tag tweet.image.variant(resize_to_fill: [700, 500]).processed, class:'tweet-pic' %>
        <p><%= tweet.content %></p>
          <% if farmer_signed_in? && current_farmer.farm.id == @farm.id%>
            <%= link_to '編集', edit_farm_tweet_path(@farm, tweet), class:"tweet-edit" %>
            <%= link_to '削除', farm_tweet_path(@farm, tweet), class:"tweet-destroy", method: :delete %>
          <% end %>
      </div>
      <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'shares/bar_menu_second' %>
<h2 class="tweet-new-title">ツイート作成ページ</h2>

  <%= form_with model: [@farm, @tweet], local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>

  <div class="tweet-new">
    <div class="tweet-inner">
      <div class='tweet-text'>
        <%= form.label :content, 'ツイート記事を入力して下さい' %><br>
        <%= form.text_area :content %>
      </div>
      <div class="tweet-image">
        <%= form.label :image, 'ツイート画像を選択して下さい(1個)' %><br>
        <%= form.file_field :image, id: 'farm-image1' %>
      </div>
      <div id='image-list'></div>
      <div class='tweet-submit'>
        <%= form.submit '作成' %>
      </div>
    </div>
  </div>
<% end %>