config/routes.rb
Rails.application.routes.draw do
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    passwords:     'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :new, :create]
  end
  resources :farms, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :tags, only: :show
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :farmer
  has_one_attached :image
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :period
  belongs_to_active_hash :ship_expense
  has_many :orders, dependent: :destroy

  validates :name, :image, :description, :ship_expense_id, :prefecture_id, :period_id, :price, presence: true
  validates :ship_expense_id, :prefecture_id, :period_id, numericality: { other_than: 1 }
  validates :name, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角カタカナで入力して下さい' }
  validates :price, format: { with: /\A[0-9]+\z/ }
  validates :price, numericality: { greater_than_or_equal_to: 100 }

  def self.search(search)
    if search != ""
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_farmer!, only: :new
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root, only: [:edit, :destroy]

  def index
    @farms = Farm.includes(:farmer)
    @items = Item.all
    @tags = Tag.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :ship_expense_id, :prefecture_id, :period_id, :price, :image).merge(farmer_id: current_farmer.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_root
    return if farmer_signed_in? && current_farmer.id == @item.farmer_id

    redirect_to root_path
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render partial: 'shares/bar_menu_second' %>
<h2 class="sign-head">商品編集</h2>

<%= form_with model: @item, local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>
  <div class="box-item">
    <div class="box-inner">
      <div class='box-text'>
        <%= form.label :name, '品目を全角カタカナで入力して下さい' %><br>
        <%= form.text_field :name, placeholder:'(例)トマト', size: '30x1' %>
      </div>
      <div class='box-text'>
        <%= form.label :description, '詳細を記入して下さい' %><br>
        <%= form.text_field :description, size: '40x1', placeholder:'(例)完熟トマト 1kg' %>
      </div>
      <div class="box-select">
        <%= form.label :image, '商品画像を選択して下さい(1個)' %><br>
        <%= form.file_field :image, id: 'farm-image1' %>
      </div>
      <div id='image-list'></div>
      <div class="box-select">
        <%= form.label :ship_expense_id, '送料負担' %><br>
        <%= form.collection_select(:ship_expense_id, ShipExpense.all, :id, :name, {}) %>
      </div>
      <div class='box-select'>
        <%= form.label :prefecture_id, '生産地' %><br>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {})%>
      </div>
      <div class='box-select'>
        <%= form.label :period_id, '発送までにかかる日数' %><br>
        <%= form.collection_select(:period_id, Period.all, :id, :name, {}) %>
      </div>
      <div class='box-text'>
        <%= form.label :price, '価格(半角数字で100以上の数値を入力して下さい)' %><br>
        <%= form.text_field :price, placeholder: '(例)1500', size: '30x1' %>
      </div>
      <div class='box-submit'>
        <%= form.submit '編集' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<%= render partial: 'shares/bar_menu' %>

<div class="top-image">
  <%= image_tag "top.png", class:"top-image-png" %>
</div>

<div class="main">
  <div class="side-bar">
    <%= form_with(url: search_items_path, local: true, method: :get, class: 'search-form') do |form| %>
      <%= form.label :keyword, "品目検索(全角カタカナ入力)", class:"search-label" %>
      <%= form.text_field :keyword, placeholder:"(例)トマト", class:"search-input" %>
      <%= form.submit "検索", class:"search-submit" %>
    <% end %>
    <%= render "shares/category", tags: @tags %>
  </div>

  <div class="main-bar">
    <h3>＜生産農園＞</h3>
    <div class="main-bar-head">

      <% @farms.each do |farm| %>
        <%= render "shares/each_farm", farm: farm %>
      <% end %>
    </div>

    <h3>＜出品農産物＞</h3>
    <div class="main-bar-bottom">
      <% @items.each do |item| %>
        <%= render "shares/each_item", item: item %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<%= render partial: 'shares/bar_menu_second' %>
<h2 class="sign-head">商品出品</h2>

<%= form_with model: @item, local: true do |form| %>
  <div class="error-messages">
    <%= render "shares/error_messages", model: form.object %>
  </div>
  <div class="box-item">
    <div class="box-inner">
      <div class='box-text'>
        <%= form.label :name, '品目を全角カタカナで入力して下さい' %><br>
        <%= form.text_field :name, placeholder:'(例)トマト', size: '30x1' %>
      </div>
      <div class='box-text'>
        <%= form.label :description, '詳細を記入して下さい' %><br>
        <%= form.text_field :description, size: '40x1', placeholder:'(例)完熟トマト 1kg' %>
      </div>
      <div class="box-select">
        <%= form.label :image, '商品画像を選択して下さい(1個)' %><br>
        <%= form.file_field :image, id: 'farm-image1' %>
      </div>
      <div id='image-list'></div>
      <div class="box-select">
        <%= form.label :ship_expense_id, '送料負担' %><br>
        <%= form.collection_select(:ship_expense_id, ShipExpense.all, :id, :name, {}) %>
      </div>
      <div class='box-select'>
        <%= form.label :prefecture_id, '生産地' %><br>
        <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {})%>
      </div>
      <div class='box-select'>
        <%= form.label :period_id, '発送までにかかる日数' %><br>
        <%= form.collection_select(:period_id, Period.all, :id, :name, {}) %>
      </div>
      <div class='box-text'>
        <%= form.label :price, '価格(半角数字で100以上の数値を入力して下さい)' %><br>
        <%= form.text_field :price, placeholder: '(例)1500', size: '30x1' %>
      </div>
      <div class='box-submit'>
        <%= form.submit '作成' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/search.html.erb
<%= render partial: 'shares/bar_menu' %>

<div class="main-bar-bottom">
  <% @items.each do |item| %>
    <%= render "shares/each_item", item: item %>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render partial: 'shares/bar_menu' %>

<div class="show-item">
  <div class="show-item-below">
    <h2 class="show-item-title">商品詳細</h2>
    <h3 class="show-item-name"><%= @item.name %></h3>
    <% if farmer_signed_in? && current_farmer.id == @item.farmer.id %>
      <div class="show-item edit">
        <%= link_to '商品編集', edit_item_path(@item), class:"item-edit" %>
        <% if @item.orders == [] %>
        <%= link_to '商品削除', item_path(@item), method: :delete, class:"item-delete" %>
        <% end %>
      </div>
    <% end %>
    <%= image_tag @item.image, class:"show-item-image" %>

    <% unless farmer_signed_in? %>
      <%= form_with(url: new_item_order_path(@item), local: true, method: :get, class: 'order-index') do |form| %>
        <%= form.label :count, "購入数量(半角数字)", class:"order-index-label" %><br>
        <%= form.text_field :count, placeholder:"(例)3", class:"order-index-input" %>
        <%= form.submit "購入ページへ進む", class:"order-index-submit" %>
      <% end %>
    <% end %>

    <table border="2" class="show-item-table">
      <tr>
        <td>商品名</td>
        <td><%= @item.description %></td>
      </tr>
      <tr>
        <td>送料</td>
        <td><%= @item.ship_expense.name %></td>
      </tr>
      <tr>
        <td>生産地</td>
        <td><%= @item.prefecture.name %></td>
      </tr>
      <tr>
        <td>生産農園</td>
        <td><%= link_to @item.farmer.farm.name, farm_path(@item.farmer.farm.id), class:"show-item-link" %>
      <tr>
        <td>発送までにかかる日数</td>
        <td><%= @item.period.name %></td>
      </tr>
      <tr>
        <td>価格</td>
        <td><%= @item.price %></td>
      </tr>
    </table>
  </div>
</div>